# Generated by Django 5.0.6 on 2024-07-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_author_postmodel_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='postmodel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
