# Generated by Django 5.0.7 on 2024-09-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='gaming_image',
            field=models.ImageField(blank=True, null=True, upload_to='gaming'),
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
