# Generated by Django 5.0.7 on 2024-09-06 16:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postmodel_gaming_image_delete_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
